default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
<% if ENV["CIRCLECI"] %>
  user: postgres
<% end %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tokite_development

test:
  <<: *default
  database: tokite_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
