version: 2
jobs:
  build:
    working_directory: ~/tokite
    docker:
      - image: cimg/ruby:2.7.5-node
      - image: cimg/postgres:14.1
    steps:
      - checkout

      - type: cache-restore
        key: gemfile-{{ checksum "Gemfile" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      - type: cache-save
        key: gemfile-{{ checksum "Gemfile" }}
        paths:
          - vendor/bundle

      # Database setup
      - run: bundle exec rake db:create
      - run: RAILS_ENV=test bundle exec rails app:tokite:ridgepole:install app:tokite:ridgepole:apply

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results
